SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES 
FROM BOOK AS B
JOIN AUTHOR AS A ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES AS BS ON BS.BOOK_ID = B.BOOK_ID
WHERE BS.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY B.AUTHOR_ID, B.CATEGORY, DATE_FORMAT(BS.SALES_DATE, '%Y-%m')
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC