
SELECT DATE_FORMAT(ONS.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, ONS.PRODUCT_ID, ONS.USER_ID, ONS.SALES_AMOUNT
FROM ONLINE_SALE AS ONS
WHERE ONS.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION ALL

SELECT DATE_FORMAT(OFS.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, OFS.PRODUCT_ID, NULL AS USER_ID, OFS.SALES_AMOUNT
FROM OFFLINE_SALE AS OFS
WHERE OFS.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID