SELECT CRCC.CAR_ID, CRCC.CAR_TYPE,
FLOOR(CRCC.DAILY_FEE * 30 * (100 - CRCDP.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCRH.CAR_ID = CRCC.CAR_ID 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP ON CRCDP.CAR_TYPE = CRCC.CAR_TYPE
WHERE CRCC.CAR_ID NOT IN 
(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-12-01') 
AND CRCDP.DURATION_TYPE = '30일 이상'
GROUP BY CRCC.CAR_ID 
HAVING CRCC.CAR_TYPE IN ('SUV', '세단') AND FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CRCC.CAR_TYPE, CRCC.CAR_ID DESC