SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES FROM REST_INFO AS RI
WHERE (RI.FOOD_TYPE, RI.FAVORITES) 
IN (SELECT RIS.FOOD_TYPE, MAX(RIS.FAVORITES) FROM REST_INFO AS RIS GROUP BY RIS.FOOD_TYPE)
ORDER BY RI.FOOD_TYPE DESC

