SELECT UGU.USER_ID, UGU.NICKNAME, 
CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) AS '전체주소', 
CONCAT(SUBSTR(UGU.TLNO, 1, 3), '-', SUBSTR(UGU.TLNO, 4, 4), '-', SUBSTR(UGU.TLNO, 8)) 
AS '전화번호' FROM USED_GOODS_USER AS UGU
LEFT JOIN (SELECT UGB.WRITER_ID, COUNT(UGB.WRITER_ID) AS COUNT FROM USED_GOODS_BOARD AS UGB GROUP BY UGB.WRITER_ID) AS UGB ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.COUNT >= 3 
ORDER BY UGU.USER_ID DESC

