
SELECT CRCRH.HISTORY_ID, CRCRH.CAR_ID, 
DATE_FORMAT(CRCRH.START_DATE, '%Y-%m-%d') AS START_DATE, 
DATE_FORMAT(CRCRH.END_DATE, '%Y-%m-%d') AS END_DATE, 
CASE WHEN DATEDIFF(CRCRH.END_DATE,CRCRH.START_DATE) >= 29
THEN '장기 대여' ELSE '단기 대여' END AS RENT_TYPE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
WHERE CRCRH.START_DATE BETWEEN '2022-09-01' AND '2022-09-30'
ORDER BY CRCRH.HISTORY_ID DESC