
SELECT FW.WAREHOUSE_ID, FW.WAREHOUSE_NAME, FW.ADDRESS, CASE WHEN FW.FREEZER_YN IS NULL THEN 'N' ELSE FW.FREEZER_YN END AS FREEZER_YN
FROM FOOD_WAREHOUSE AS FW
WHERE FW.ADDRESS LIKE '%경기도%'
ORDER BY WAREHOUSE_ID