SELECT SD.ROUTE, 
CONCAT(ROUND(SUM(SD.D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, 
CONCAT(ROUND(SUM(SD.D_BETWEEN_DIST) / COUNT(SD.ROUTE), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE AS SD
GROUP BY SD.ROUTE
ORDER BY ROUND(SUM(SD.D_BETWEEN_DIST), 1) DESC;
