SELECT COUNT(FI.FISH_TYPE) AS FISH_COUNT, FNI.FISH_NAME FROM FISH_INFO AS FI
LEFT JOIN FISH_NAME_INFO AS FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
GROUP BY FI.FISH_TYPE, FNI.FISH_NAME ORDER BY FISH_COUNT DESC

