SELECT CRCRH.CAR_ID, 
CASE WHEN CRCRH.CAR_ID IN 
(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') THEN '대여중'
ELSE '대여 가능' END AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
GROUP BY CRCRH.CAR_ID
ORDER BY CRCRH.CAR_ID DESC