
SELECT fr.PRODUCT_ID, fr.PRODUCT_NAME, SUM(fr.PRICE * fo.AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT AS fr 
JOIN FOOD_ORDER AS fo ON fo.PRODUCT_ID = fr.PRODUCT_ID WHERE DATE_FORMAT(fo.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY fr.PRODUCT_ID, fr.PRODUCT_NAME ORDER BY TOTAL_SALES DESC, fr.PRODUCT_ID ASC