SELECT CRCRH.HISTORY_ID,
FLOOR(
CASE WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 BETWEEN 7 AND 29 THEN 
CRCC.DAILY_FEE * (1 - (SELECT DISCOUNT_RATE / 100.0 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')) * (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1)
WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 BETWEEN 30 AND 89 THEN
CRCC.DAILY_FEE * (1 - (SELECT DISCOUNT_RATE / 100.0 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')) * (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1)
WHEN DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 >= 90 THEN
CRCC.DAILY_FEE * (1 - (SELECT DISCOUNT_RATE / 100.0 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')) * (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1)
ELSE CRCC.DAILY_FEE * (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1)
END) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS CRCC ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CRCRH.HISTORY_ID DESC