SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE MP.MEMBER_ID = (SELECT RR.MEMBER_ID FROM REST_REVIEW AS RR GROUP BY RR.MEMBER_ID ORDER BY COUNT(RR.MEMBER_ID) DESC LIMIT 1)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT