SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, MAX_SIZE_ED.SIZE - ED.SIZE_OF_COLONY AS YEAR_DEV, ED.ID 
FROM ECOLI_DATA AS ED
JOIN (SELECT MAX(SIZE_OF_COLONY) AS SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR 
      FROM ECOLI_DATA GROUP BY YEAR) AS MAX_SIZE_ED 
      ON MAX_SIZE_ED.YEAR = YEAR(ED.DIFFERENTIATION_DATE) 
ORDER BY YEAR, YEAR_DEV