
SELECT CRCRH.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
JOIN CAR_RENTAL_COMPANY_CAR AS CRCC ON CRCC.CAR_ID = CRCRH.CAR_ID 
WHERE CRCC.CAR_TYPE = '세단' AND CRCRH.START_DATE LIKE '%2022-10%'
GROUP BY CRCRH.CAR_ID
ORDER BY CRCRH.CAR_ID DESC

# SELECT * FROM CAR_RENTAL_COMPANY_CAR AS CRCC WHERE CRCC.CAR_TYPE = '세단'