SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO
WHERE LENGTH IS NOT NULL GROUP BY FISH_TYPE) AS MAX_FISH_INFO
ON FI.FISH_TYPE = MAX_FISH_INFO.FISH_TYPE AND FI.LENGTH = MAX_FISH_INFO.LENGTH
ORDER BY FI.ID