SELECT SUM(HG.SCORE) AS SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL FROM HR_EMPLOYEES AS HE
LEFT JOIN HR_GRADE AS HG ON HG.EMP_NO = HE.EMP_NO
WHERE HG.YEAR = '2022'
GROUP BY HE.EMP_NO
ORDER BY SCORE DESC LIMIT 1