
SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS UGF
WHERE UGF.BOARD_ID = (SELECT UGB.BOARD_ID FROM USED_GOODS_BOARD AS UGB ORDER BY UGB.VIEWS DESC LIMIT 1)
ORDER BY UGF.FILE_ID DESC
