SELECT FP.CATEGORY,  MAX(FP.PRICE) AS MAX_PRICE, FP.PRODUCT_NAME 
FROM FOOD_PRODUCT AS FP
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY FP.CATEGORY, FP.PRODUCT_NAME
HAVING MAX(FP.PRICE) = (SELECT MAX(PRICE) FROM FOOD_PRODUCT WHERE CATEGORY = FP.CATEGORY)
ORDER BY MAX_PRICE DESC